trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - 'v*'

strategy:
  matrix:
    MacOs Python3.7:
      image: 'macos-latest'
      python.version: '3.7'
      python.architecture: 'x64'
    MacOs Python3.8:
      image: 'macos-latest'
      python.version: '3.8'
      python.architecture: 'x64'
    MacOs Python3.9:
      image: 'macos-latest'
      python.version: '3.9'
      python.architecture: 'x64'
    MacOs Python3.10:
      image: 'macos-latest'
      python.version: '3.10'
      python.architecture: 'x64'
    Ubuntu Python3.7:
      image: 'ubuntu-latest'
      python.version: '3.7'
      python.architecture: 'x64'
    Ubuntu Python3.8:
      image: 'ubuntu-latest'
      python.version: '3.8'
      python.architecture: 'x64'
    Ubuntu Python3.9:
      image: 'ubuntu-latest'
      python.version: '3.9'
      python.architecture: 'x64'
    Ubuntu Python3.10:
      image: 'ubuntu-latest'
      python.version: '3.10'
      python.architecture: 'x64'
    Windows Python3.7 (x86):
      image: 'windows-latest'
      python.version: '3.7'
      python.architecture: 'x86'
    Windows Python3.7 (x64):
      image: 'windows-latest'
      python.version: '3.7'
      python.architecture: 'x64'
    Windows Python3.8 (x86):
      image: 'windows-latest'
      python.version: '3.8'
      python.architecture: 'x86'
    Windows Python3.8 (x64):
      image: 'windows-latest'
      python.version: '3.8'
      python.architecture: 'x64'
    Windows Python3.9 (x86):
      image: 'windows-latest'
      python.version: '3.9'
      python.architecture: 'x86'
    Windows Python3.9 (x64):
      image: 'windows-latest'
      python.version: '3.9'
      python.architecture: 'x64'
    Windows Python3.10 (x86):
      image: 'windows-latest'
      python.version: '3.10'
      python.architecture: 'x86'
    Windows Python3.10 (x64):
      image: 'windows-latest'
      python.version: '3.10'
      python.architecture: 'x64'

pool:
  vmImage: $(image)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'
  - bash: python -m pip install --upgrade pip setuptools
    displayName: 'Install packaging tools'
  - bash: python setup.py install
    displayName: 'Install'
  - bash: python -m pip install --upgrade coverage codecov
    displayName: 'Install coverage dependencies'
  - bash: coverage run -m doctest README.md
    displayName: 'Run doctests'
  - bash: python -m pip install -r requirements-tests.txt
    displayName: 'Install tests dependencies'
  - bash: coverage run --append -m pytest
    displayName: 'Run tests'
  - bash: coverage xml
    displayName: 'Collect coverage'
  - bash: python -m codecov -f coverage.xml -X gcov --build "$AGENT_JOBNAME"
    condition: succeeded()
    displayName: 'Upload coverage'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
  - ${{ if and(eq(variables['python.version'], '3.7'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    - bash: python -m pip install --upgrade wheel
      condition: succeeded()
      displayName: 'Install build dependencies'
    - bash: python setup.py sdist bdist_wheel
      condition: succeeded()
      displayName: 'Build'
    - bash: python -m pip install --upgrade twine
      condition: succeeded()
      displayName: 'Install deploy dependencies'
    - bash: twine upload --skip-existing dist/*
      condition: succeeded()
      displayName: 'Deploy'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $(TWINE_PASSWORD)
  - ${{ if or(ne(variables['PYTHON_VERSION'], '3.7'), startsWith(variables['BUILD_SOURCEBRANCH'], 'refs/tags/')) }}:
    - bash: printenv
      displayName: 'Print environment'
